### ISSUE TITLE
time in H:MM format in schedules (6:15 vs 06:15) crashess app

### ISSUE THREAD

**Issue by mradziwo** [efficiosoft/hass-heaty#2]
putting time in H:MM format (e.g. 6:55) crashes the app without warning. 
I have fallen already several times in this pitfall, and quick cure is to correct time format for HH:MM (06:55).

However it would be great if hass_apps could recognize H:MM format

**Comment by efficiosoft** [comment]
Hi,

please open the issue on the right project. The hass-heaty repository is deprecated as mentioned in the README. I'm now going to disable the issue component completely here in order to avoid issues opened by mistake.

Best regards
Robert
